---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.5.1

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: centos-6.8
- name: centos-7.2
- name: debian-7.11
- name: debian-8.6
- name: fedora-23
- name: fedora-24
- name: opensuse-leap-42.1
- name: opensuse-13.2

verifier:
  name: inspec

suites:
- name: default
  run_list:
  - recipe[ssh-hardening]
  verifier:
    inspec_tests:
      - https://github.com/dev-sec/tests-ssh-hardening
