---
driver:
  name: dokken
#  chef_version: 12.5.1
#  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken
#  name: chef_solo
  #test_repo_uri: https://github.com/TelekomLabs/tests-ssh-hardening.git

verifier:
  name: inspec
  sudo: true

platforms:
- name: ubuntu
  driver:
    image: ubuntu:14.04

suites:
- name: default
  run_list:
  - - role[ssh]
