---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.5.1

platforms:
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: centos-6.8
- name: centos-7.3
- name: oracle-6.8
- name: oracle-7.3
- name: debian-7.11
- name: debian-8.6
- name: fedora-24
- name: fedora-25
- name: opensuse-leap-42.1

verifier:
  name: inspec

suites:
- name: default
  run_list:
  - recipe[test]
  - recipe[ssh-hardening]
  verifier:
    inspec_tests:
      - https://github.com/dev-sec/tests-ssh-hardening
- name: rhel-with-disabled-pam
  includes:
    - centos-6.8
    - centos-7.3
    - fedora-24
    - fedora-25
    - oracle-6.8
    - oracle-7.3
  driver:
    provision: true
    vagrantfiles:
      - test/fixtures/vagrantfiles/enforce_selinux.rb
  run_list:
  - recipe[test]
  - recipe[ssh-hardening]
  attributes:
    ssh-hardening:
      ssh:
        server:
          use_pam: false
  verifier:
    inspec_tests:
      - https://github.com/dev-sec/tests-ssh-hardening
      - test/integration/without-pam
