---
sudo: required
language: ruby
bundler_args: "--without development"
dist: trusty
cache: bundler

services:
- docker

rvm: 2.4.1

before_install:
  - gem update --system # see https://github.com/bundler/bundler/issues/5357

env:
 - INSTANCE=ubuntu-14-04
 - INSTANCE=ubuntu-16-04
 - INSTANCE=ubuntu-16-04 CHEF_VERSION=12.5.1
 - INSTANCE=centos-6
 - INSTANCE=centos-7
 - INSTANCE=centos-7 CHEF_VERSION=12.5.1
 - INSTANCE=oracle-6
 - INSTANCE=oracle-7
 - INSTANCE=debian-7
 - INSTANCE=debian-8
 - INSTANCE=fedora-24
 - INSTANCE=fedora-25
 - INSTANCE=opensuse-42
 - INSTANCE=opensuse-42 CHEF_VERSION=12.5.1
 - INSTANCE=amazonlinux-1
 - INSTANCE=amazonlinux-2

script:
  -  bundle exec rake kitchen KITCHEN_LOCAL_YAML=.kitchen.dokken.yml

matrix:
  include:
    - env: UNIT_AND_LINT=1
      script:
        - bundle exec rake lint spec
